# Generated by Django 6.1.1 on 2026-10-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='job_role',
            field=models.CharField(blank=True, default='General Profile', max_length=200),
        ),
    ]
