# Generated by Django 6.1.1 on 2026-10-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_resumeanalysis_job_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='seniority_level',
            field=models.CharField(blank=True, default='Mid-Level', max_length=50),
        ),
    ]
